version: '3'

services:
  # client:
  #   volumes:
  #     - ./client:/app
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  #     - WATCHPACK_POLLING=true
  server:
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - 8080:8080
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
  mongo_db:
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db
