version: '3'

services:
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - PORT=8080
      - MONGODB_URI=mongodb://mongo_db:27017
      - DB_NAME=db
  mongo_db:
    container_name: mongo_db
    image: mongo:latest
    restart: always

volumes:
  mongo_db:
