version: '3'

services:
  server:
    volumes:
      - ./server:/app
    ports:
      - 8080:8080
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
  mongo_db:
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db
