version: '3'

services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - SERVER_URL="http://server:8080"
    depends_on:
      - server
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - PORT=8080
      - MONGODB_URI=mongodb://mongo_db:27017
      - DB_NAME=db
    depends_on:
      - mongo_db
  mongo_db:
    container_name: mongo_db
    image: mongo:latest
    restart: always

volumes:
  mongo_db:
