version: '3.7'

services:
  # client:
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./client:/app
  #   ports:
  #     - 3000:3000
  #   environment:
  #     - WDS_SOCKET_HOST: 127.0.0.1
  #     - WDS_SOCKET_PORT: 3000
  #     - CHOKIDAR_USEPOLLING: true
  #     - WATCHPACK_POLLING: true
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - MONGODB_URI=mongodb://mongo_db:27017
      - DB_NAME=db
      - JWT_SECRET=Ifg720wYyjE8bWmi69LnjvnmMbDxa6ZjOAIK0eGJLm0=
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
  mongo_db:
    image: mongo:latest
    command: mongod --quiet --logpath /dev/null
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db

volumes:
  mongo_db:
